=== Malexba/FTI/recetarioCSS.dtd
<!ELEMENT recetario (receta+)>
<!ELEMENT receta (titulo, imagenFinal?, datos, ingredientes, procedimiento, elementosElaboracion, opcional?)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT imagenFinal EMPTY>
        <!ATTLIST imagenFinal src ENTITY #IMPLIED>
    <!ELEMENT datos (tipo, nPersonas?, dificultad, tiempo, calorias?)>
        <!ELEMENT tipo (#PCDATA)>
            <!ATTLIST tipo definicion (entrante | primero | segundo | postre) #REQUIRED>
            <!ATTLIST tipo celiacos (si | no) #IMPLIED>
            <!ATTLIST tipo vegetariano (si | no) #IMPLIED>
        <!ELEMENT nPersonas (#PCDATA)>
        <!ELEMENT dificultad (#PCDATA)>
        <!ELEMENT tiempo (#PCDATA)>
        <!ELEMENT calorias (#PCDATA)>
    <!ELEMENT ingredientes (ingrediente+)>
        <!ELEMENT ingrediente (nombre, cantidad?)>
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT procedimiento (paso+)>
        <!ELEMENT paso (#PCDATA)>
            <!ATTLIST paso orden CDATA #REQUIRED>
    <!ELEMENT elementosElaboracion (utensilio+)>
        <!ELEMENT utensilio (#PCDATA)>
    <!ELEMENT opcional (autor?, temporada?, bebida?, consejoChef?)>
        <!ELEMENT autor (#PCDATA)>
        <!ELEMENT temporada EMPTY>
            <!ATTLIST temporada epoca (OtoÃ±o | Invierno | Primavera | Verano) #REQUIRED>
        <!ELEMENT bebida (#PCDATA)>
        <!ELEMENT consejoChef (#PCDATA)>

=== Malexba/FTI/recetarioCSS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recetario  SYSTEM "recetarioCSS.dtd">
<?xml-stylesheet href="recetarioCSS.CSS" type="text/css" ?>
<recetario>
    <receta>
        <titulo>Huevos rellenos</titulo>
        <imagenFinal />
        <datos>
            <tipo definicion="entrante" celiacos="si">Frio</tipo>
            <nPersonas>4 personas</nPersonas>
            <dificultad>Fácil</dificultad>
            <tiempo>30 minutos</tiempo>
            <calorias>113 por unidad</calorias>
        </datos>
        <ingredientes>
            <ingrediente>
                <nombre>Huevos</nombre>
                <cantidad>12</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Bonito en conserva en aceite</nombre>
                <cantidad>200 gramos</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Pimiento morron</nombre>
                <cantidad>1 lata</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Sal</nombre>
            </ingrediente>
            <ingrediente>
                <nombre>Mayonesa</nombre>
                <cantidad>3 cucharadas</cantidad>
            </ingrediente>
        </ingredientes>
        <procedimiento>
            <paso orden="1">Cocer los huevos y pelarlos una vez fríos. Partirlos a la mitad y sacar todas las yemas con cuidado.</paso>
            <paso orden="2">En un cuenco aparte poner las yemas, reservando una, el bonito escurrido, el pimiento morron troceado, tres cucharadas de mayonesa y sal.</paso>
            <paso orden="3">Mezclar bien todo con un tenedor, a la vez que presionamos para deshacer los ingredientes.</paso>
            <paso orden="4">Rellenamos con esta mezcla cada mitad de un huevo. Cubrir con un poco mayonesa. Conservar en la nevera</paso>
            <paso orden="5">Servir adornando con unas tiras de pimiento y yema rallada.</paso>
        </procedimiento>
        <elementosElaboracion>
            <utensilio>Olla</utensilio>
        </elementosElaboracion>
        <opcional>
            <autor>www.directoalpaladar.com</autor>
        <consejoChef> Mucho más rico con mayonesa casera.</consejoChef>
        </opcional>
    </receta>
    <receta>
        <titulo>Ensalada de tofu</titulo>
        <imagenFinal />
        <datos>
            <tipo definicion="entrante" vegetariano="si">Ensaladas</tipo>
            <nPersonas>2 personas</nPersonas>
            <dificultad>Fácil</dificultad>
            <tiempo>10 minutos</tiempo>
        </datos>
        <ingredientes>
            <ingrediente>
                <nombre>Tofu</nombre>
                <cantidad>150 gramos</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Canónigos</nombre>
                <cantidad>150 gramos</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Lechuga variada</nombre>
                <cantidad>100 gramos</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Brotes de soja</nombre>
                <cantidad>50 gramos</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Pepino</nombre>
                <cantidad>Medio</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Nueces</nombre>
                <cantidad>8 ó 9</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Cebollitas en vinagre</nombre>
                <cantidad>2</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Mostaza</nombre>
                <cantidad>1 cucharada</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Leche de soja</nombre>
                <cantidad>3 cucharadas</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Pimienta negra</nombre>
            </ingrediente>
            <ingrediente>
                <nombre>Sal</nombre>
            </ingrediente>
            <ingrediente>
                <nombre>Aceite de oliva</nombre>
            </ingrediente>
        </ingredientes>
        <procedimiento>
            <paso orden="1">Echar en una ensaladera los canónigos y lechuga, cortar el pepino en rodajas e incorporar junto con las cebolllitas.</paso>
            <paso orden="2">Cortar el tofu en cuadraditos y añadirlos junto con los brotes de soja.</paso>
            <paso orden="3">Para el aliño, mezclar en un bol el aceite, mostaza, leche de soja.</paso>
            <paso orden="4">Disponer el aliño por encima de la ensalada y rectificar de pimienta y sal.</paso>
        </procedimiento>
        <elementosElaboracion>
            <utensilio>Ensaladera</utensilio>
        </elementosElaboracion>
        <opcional>
            <autor>www.okdiario.com/recetas</autor>
        </opcional>
    </receta>
    <receta>
        <titulo>Arroz con Mejillones</titulo>
        <imagenFinal />
        <datos>
            <tipo definicion="primero">Arroces</tipo>
            <nPersonas>3 personas</nPersonas>
            <dificultad>Medio</dificultad>
            <tiempo>45 minutos</tiempo>
        </datos>
        <ingredientes>
            <ingrediente>
                <nombre>Mejillones</nombre>
                <cantidad>24</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Arroz</nombre>
                <cantidad>300 gramos</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Pimiento verde</nombre>
                <cantidad>1</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Cebolleta</nombre>
                <cantidad>1</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Puerro</nombre>
                <cantidad>1</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Tomate</nombre>
                <cantidad>1</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Dientes ajo</nombre>
                <cantidad>2</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Sal</nombre>
            </ingrediente>
            <ingrediente>
                <nombre>Aceite de oliva</nombre>
            </ingrediente>
        </ingredientes>
        <procedimiento>
            <paso orden="1">Limpiar los mejillones, cocerlos en agua con sal, reservar los mejillones y el caldo restante</paso>
            <paso orden="2">Rehogar el pimiento, la cebolleta, el perro, los dientes de ajo y el tomate picados finamente y sazonar.</paso>
            <paso orden="3">Agregar el arroz, la mitad de los mejillones sin cáscara, el caldo de coer los mejillones. Sazonar de nuevo y cocinarlo duratne 15-18 minutos</paso>
            <paso orden="4">Cuando este a punto, decora con el resto de los mejillones</paso>
        </procedimiento>
        <elementosElaboracion>
            <utensilio>Tartera</utensilio>
        </elementosElaboracion>
        <opcional>
            <autor>Karlos Arguiñano</autor>
            <temporada epoca="Otoño"></temporada>
            <bebida>Cava</bebida>
            <consejoChef>Ponerle un poquito de perejil para decorar</consejoChef>
        </opcional>
    </receta>
    <receta>
        <titulo>Lentejas con chorizo</titulo>
        <imagenFinal />
        <datos>
            <tipo definicion="primero">Legumbres</tipo>
            <nPersonas>6 personas</nPersonas>
            <dificultad>Medio</dificultad>
            <tiempo>90 minutos</tiempo>
        </datos>
        <ingredientes>
            <ingrediente>
                <nombre>Lentejas</nombre>
                <cantidad>500 gramos</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Zanahorias</nombre>
                <cantidad>4</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Pimiento verde</nombre>
                <cantidad>1</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Cebollas</nombre>
                <cantidad>2</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Laurel</nombre>
                <cantidad>1 hoja</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Pimientón de la vera</nombre>
                <cantidad>1 cucharada</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Tomate</nombre>
                <cantidad>2</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Chorizos</nombre>
                <cantidad>2</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Dientes ajo</nombre>
                <cantidad>2</cantidad>
            </ingrediente>
            <ingrediente>
                <nombre>Sal</nombre>
            </ingrediente>
            <ingrediente>
                <nombre>Pimienta negra</nombre>
            </ingrediente>
            <ingrediente>
                <nombre>Aceite de oliva</nombre>
            </ingrediente>
        </ingredientes>
        <procedimiento>
            <paso orden="1">Picamos la cebolla, el ajo, el pimiento, las zanahorias y los tomates</paso>
            <paso orden="2">En una cazuela con aceite sofreimos la cebolla y dientes de ajo. Añadimos el pimiento, tomate, zanahorias y la hoja de laurel y lo sofreimos unos minutos. Incorporar el pimentón</paso>
            <paso orden="3">Lavar las lentejas, escurrirlas. Añadir a la cazuela y remover para que se junte todo</paso>
