=== Malexba/FTI/PRACTICA XML/recetario.dtd
<!ELEMENT recetario (receta+)>
<!ELEMENT receta  (nombre, imagenFinal?,tipo,dificultad,tiempo, calorias?, ingredientes,  procedimiento,   elementosElaboración, autor?,temporada?,bebida?,consejoChef?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT imagenFinal (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ATTLIST tipo definicion (entrante | primero | segundo | postre) #REQUIRED>
<!ATTLIST tipo celiacos (si | no) #IMPLIED>
<!ATTLIST tipo vegetariano (si | no) #IMPLIED>
<!ELEMENT ingredientes (ingrediente+,imagenIngredientes?)>
<!ELEMENT imagenIngredientes (#PCDATA)>
<!ATTLIST ingredientes personas CDATA #IMPLIED>
<!ELEMENT ingrediente (#PCDATA)>
<!ATTLIST ingrediente nombre CDATA #REQUIRED>
<!ATTLIST ingrediente cantidad CDATA #IMPLIED>
<!ELEMENT calorias (#PCDATA)>
<!ELEMENT procedimiento (paso+)>
<!ELEMENT paso (#PCDATA)>
<!ATTLIST paso orden CDATA #REQUIRED>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT dificultad (#PCDATA)>
<!ELEMENT elementosElaboración (utensilio+)>
<!ELEMENT utensilio (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT temporada EMPTY>
<!ATTLIST temporada epoca (Otoño | Invierno | Primavera | Verano) #REQUIRED>
<!ELEMENT bebida (#PCDATA)>
<!ELEMENT consejoChef (#PCDATA)>

=== Malexba/FTI/PRACTICA XML/recetario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recetario  SYSTEM "recetario.dtd">
<recetario>
    <receta>
        <nombre>Tarta de chocolate</nombre>
        <imagenFinal></imagenFinal>
        <tipo definicion="postre">Postre ligero</tipo>
        <dificultad>Facil</dificultad>
        <tiempo>45 minutos</tiempo>
        <calorias>650</calorias>
        <ingredientes>
            <ingrediente nombre="harina" cantidad="200 gramos"></ingrediente>
        </ingredientes>
        <procedimiento>
            <paso orden="1">Mezclar los ingredientes</paso>
        </procedimiento>
        <elementosElaboración>
            <utensilio>Horno</utensilio>
        </elementosElaboración>
        <origen></origen>
        <temporada epoca="Otoño"></temporada>
        <bebida>Tinto</bebida>
        <consejoChef></consejoChef>
    </receta>
</recetario>
